version: '2'
services:
  uaa-app:
    image: uaa
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://uaa-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=uaa
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  uaa-mongodb:
    extends:
      file: mongodb.yml
      service: uaa-mongodb
