version: '2'
services:
  quotes-app:
    image: quotes
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://quotes-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=quotes
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  quotes-mongodb:
    extends:
      file: mongodb.yml
      service: quotes-mongodb
